name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 00:00 检查一次上游更新
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出你的仓库
      - name: Checkout your branch
        uses: actions/checkout@v3
        with:
          ref: master # 替换为你的分支名称
          fetch-depth: 0 # 获取完整的提交历史

      # 2. 添加上游仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/DIYgod/RSSHub.git
          git fetch upstream

      # 3. 合并上游分支到你的分支
      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master # 替换为你的分支名称
          git merge upstream/master # 替换为上游分支名称

      # 4. 推送更新到你的分支
      - name: Push changes
        run: |
          git push origin master # 替换为你的分支名称